# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import base64
import json
import logging
import os
import re
from typing import Any

import google.auth
from dotenv import load_dotenv
from google.adk.agents import LlmAgent
from google.adk.agents.context import Context
from google.adk.apps import App
from google.adk.events.event import Event
from google.adk.events.request_input import RequestInput
from google.adk.workflow import START, Workflow, node
from pydantic import BaseModel, Field

# Load environment variables from .env file
load_dotenv()

logger = logging.getLogger(__name__)

# Try to load Google Cloud credentials. If not available, look for environment variables or fail gracefully.
project_id = os.getenv("GOOGLE_CLOUD_PROJECT")
if not project_id:
    try:
        _, project_id = google.auth.default()
        if project_id:
            os.environ["GOOGLE_CLOUD_PROJECT"] = project_id
    except Exception as e:
        logger.warning(
            f"Could not load application default credentials: {e}. If using Google AI Studio, make sure GEMINI_API_KEY is set."
        )

# Default settings if not already defined
if "GOOGLE_CLOUD_LOCATION" not in os.environ:
    os.environ["GOOGLE_CLOUD_LOCATION"] = "global"

# Load config.json
DIR_PATH = os.path.dirname(os.path.abspath(__file__))
config_path = os.path.join(DIR_PATH, "config.json")
try:
    with open(config_path) as f:
        config = json.load(f)
except Exception as e:
    logger.error(f"Failed to load config.json: {e}")
    config = {"threshold": 100.0, "model": "gemini-3.1-flash-lite"}

THRESHOLD = config.get("threshold", 100.0)
MODEL_NAME = config.get("model", "gemini-3.1-flash-lite")


# Define Pydantic schemas for structured input/output validation
class EventInput(BaseModel):
    """The root event input schema containing the data key."""

    data: Any = Field(
        description="The expense data payload or a base64-encoded string containing it"
    )


class ExpenseOutput(BaseModel):
    """The final structured output record of the expense processing."""

    approved: bool
    amount: float
    submitter: str
    category: str
    description: str
    date: str
    risk_rating: str
    risk_factors: list[str]
    comments: str
    redacted_categories: list[str] = []


class RiskReview(BaseModel):
    """Structured risk review output generated by the LLM."""

    risk_rating: str = Field(description="Risk assessment: LOW, MEDIUM, or HIGH")
    risk_factors: list[str] = Field(
        description="List of specific risk factor descriptions found"
    )


# Helper functions for Security Checkpoint
def scrub_pii(description: str) -> tuple[str, list[str]]:
    """Scrubs SSNs and Credit Card numbers from the text and returns categories redacted."""
    redacted_categories = []

    # Format: XXX-XX-XXXX
    ssn_pattern = re.compile(r"\b\d{3}-\d{2}-\d{4}\b")
    # Format: 13-16 digit numbers with optional dashes or spaces
    cc_pattern = re.compile(r"\b\d{4}[- ]?\d{4}[- ]?\d{4}[- ]?\d{4}\b|\b\d{16}\b")

    scrubbed = description
    if ssn_pattern.search(scrubbed):
        scrubbed = ssn_pattern.sub("[REDACTED SSN]", scrubbed)
        redacted_categories.append("SSN")

    if cc_pattern.search(scrubbed):
        scrubbed = cc_pattern.sub("[REDACTED CREDIT CARD]", scrubbed)
        redacted_categories.append("Credit Card")

    return scrubbed, redacted_categories


def detect_prompt_injection(description: str) -> bool:
    """Checks the description for common prompt injection patterns."""
    injection_keywords = [
        "ignore previous instructions",
        "ignore the above",
        "system prompt override",
        "override system instructions",
        "you are now an auto-approver",
        "auto-approve this",
        "force approve",
        "skip check",
        "bypass rules",
        "do not review",
        "trust this expense",
        "approve without checking",
        "ignore rules",
    ]
    desc_lower = description.lower()
    return any(kw in desc_lower for kw in injection_keywords)


# Define function nodes for our graph workflow
def extract_expense(ctx: Context, node_input: EventInput) -> Event:
    """Extracts and decodes the expense payload from base64 or plain JSON."""
    raw_data = node_input.data
    decoded_str = None

    if isinstance(raw_data, str):
        try:
            # Attempt to decode as base64 (with padding compensation)
            padded = raw_data + "=" * (-len(raw_data) % 4)
            decoded_bytes = base64.b64decode(padded, validate=True)
            decoded_str = decoded_bytes.decode("utf-8")
        except Exception:
            # If not valid base64, treat it as a raw JSON string
            decoded_str = raw_data

    if decoded_str is not None:
        try:
            expense_details = json.loads(decoded_str)
        except Exception as e:
            raise ValueError(f"Failed to parse decoded string as JSON: {e}") from e
    elif isinstance(raw_data, dict):
        expense_details = raw_data
    else:
        raise ValueError(
            "Invalid format: 'data' must be a base64 string, JSON string, or dict."
        )

    # Standardize field names and default values
    expense = {
        "amount": float(expense_details.get("amount", 0.0)),
        "submitter": str(expense_details.get("submitter", "Unknown")),
        "category": str(expense_details.get("category", "General")),
        "description": str(expense_details.get("description", "No description")),
        "date": str(expense_details.get("date", "N/A")),
    }

    # Store extracted expense in state so other nodes can access it
    return Event(output=expense, state={"expense": expense})


def route_expense(ctx: Context, node_input: dict) -> Event:
    """Routes the workflow based on the expense amount threshold."""
    amount = node_input["amount"]
    if amount < THRESHOLD:
        return Event(output=node_input, route="under_threshold")
    return Event(output=node_input, route="above_threshold")


def auto_approve(ctx: Context, node_input: dict) -> Event:
    """Instantly auto-approves expenses under the threshold."""
    return Event(
        output={
            "approved": True,
            "risk_rating": "none",
            "risk_factors": [],
            "comments": f"Auto-approved: amount (${node_input['amount']}) is under the threshold (${THRESHOLD}).",
        }
    )


def security_checkpoint(ctx: Context, node_input: dict) -> Event:
    """PII Scrubbing and Prompt Injection Defense checkpoint node."""
    expense = ctx.state["expense"]
    description = expense.get("description", "")

    # 1. Scrub PII (SSN and Credit Card)
    scrubbed_desc, redacted_categories = scrub_pii(description)
    expense["description"] = scrubbed_desc

    # Persist updated expense and redacted categories in state
    ctx.state["expense"] = expense
    ctx.state["redacted_categories"] = redacted_categories

    # 2. Check for Prompt Injection
    if detect_prompt_injection(scrubbed_desc):
        # Defend: Bypass LLM reviewer and route straight to human approval
        redacted_info = (
            f" (Redacted PII: {', '.join(redacted_categories)})"
            if redacted_categories
            else ""
        )
        return Event(
            output={
                "risk_rating": "HIGH",
                "risk_factors": [
                    "PROMPT INJECTION ATTEMPT DETECTED",
                    "SECURITY EXCEPTION",
                ],
                "comments": f"Bypassed LLM Review: Security block triggered due to prompt injection keywords in description.{redacted_info}",
            },
            route="flagged_security_event",
        )

    # Clean: Proceed to LLM risk reviewer
    return Event(output=expense, route="clean")


# Define LLM node for risk analysis
risk_reviewer = LlmAgent(
    name="risk_reviewer",
    model=MODEL_NAME,
    instruction=(
        "You are an AI Risk Auditor. Analyze the provided expense report details "
        "and assess potential risk factors (e.g. suspicious categories, unusual amounts, "
        "or vague descriptions).\n"
        "Return a structured evaluation containing:\n"
        "1. risk_rating: 'LOW', 'MEDIUM', or 'HIGH'.\n"
        "2. risk_factors: A list of specific risk factor descriptions found."
    ),
    output_schema=RiskReview,
)


@node(name="review_agent", rerun_on_resume=True)
async def review_agent(ctx: Context, node_input: Any):
    """Pauses workflow to request human review after raising a risk or security alert."""
    expense = ctx.state["expense"]
    redacted_categories = ctx.state.get("redacted_categories", [])

    # Handle both dict and parsed object for LLM structured output
    if isinstance(node_input, dict):
        risk_rating = node_input.get("risk_rating", "UNKNOWN")
        risk_factors = node_input.get("risk_factors", [])
        comments = node_input.get("comments", "")
    else:
        risk_rating = getattr(node_input, "risk_rating", "UNKNOWN")
        risk_factors = getattr(node_input, "risk_factors", [])
        comments = ""

    factors_str = ", ".join(risk_factors) if risk_factors else "None"
    redacted_str = ", ".join(redacted_categories) if redacted_categories else "None"

    # Display clean/scrubbed description in human verification alert
    alert_msg = (
        f"\n⚠️  REVIEW REQUIRED: Expense of ${expense['amount']} by {expense['submitter']} ⚠️\n"
        f"--------------------------------------------------\n"
        f"Date:        {expense['date']}\n"
        f"Category:    {expense['category']}\n"
        f"Description: {expense['description']}\n"
        f"Redactions:  {redacted_str}\n"
        f"Risk Rating: {risk_rating}\n"
        f"Risk Factors: {factors_str}\n"
    )

    if comments:
        alert_msg += f"Security Alert: {comments}\n"

    alert_msg += (
        "--------------------------------------------------\n"
        "Approve this expense? (yes/no)"
    )

    if not ctx.resume_inputs or "approval" not in ctx.resume_inputs:
        yield RequestInput(interrupt_id="approval", message=alert_msg)
        return

    user_response = ctx.resume_inputs["approval"]
    approved = user_response.strip().lower() in ["yes", "y", "approve", "approved"]

    yield Event(
        output={
            "approved": approved,
            "risk_rating": risk_rating,
            "risk_factors": risk_factors,
            "comments": f"Human review decision: {'Approved' if approved else 'Rejected'} (User input: '{user_response}')"
            + (f" | {comments}" if comments else ""),
        }
    )


def finalize_expense(ctx: Context, node_input: dict) -> ExpenseOutput:
    """Assembles the final output structure combining original details and approval outcomes."""
    expense = ctx.state["expense"]
    redacted_categories = ctx.state.get("redacted_categories", [])
    return ExpenseOutput(
        approved=node_input["approved"],
        amount=expense["amount"],
        submitter=expense["submitter"],
        category=expense["category"],
        description=expense["description"],
        date=expense["date"],
        risk_rating=node_input.get("risk_rating", "none"),
        risk_factors=node_input.get("risk_factors", []),
        comments=node_input.get("comments", ""),
        redacted_categories=redacted_categories,
    )


# Wire up the Workflow graph topology with the Security Checkpoint
edges = [
    (START, extract_expense),
    (extract_expense, route_expense),
    # Route based on threshold check
    (
        route_expense,
        {"under_threshold": auto_approve, "above_threshold": security_checkpoint},
    ),
    # Security checkpoint routing
    (
        security_checkpoint,
        {"clean": risk_reviewer, "flagged_security_event": review_agent},
    ),
    # Normal risk review path proceeds to human approval
    (risk_reviewer, review_agent),
    # Both paths merge into finalization
    (auto_approve, finalize_expense),
    (review_agent, finalize_expense),
]

root_agent = Workflow(
    name="expense_agent",
    edges=edges,
    input_schema=EventInput,
    output_schema=ExpenseOutput,
    description="An ambient expense agent that tracks and processes expense reports with automated, secure, and human-in-the-loop review steps.",
)

app = App(
    root_agent=root_agent,
    name="expense_agent",
)
